apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-message-configmap
  namespace: default  # change if you're using a different namespace
data:
  welcome_message.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome Page</title>
    </head>
    <body>
        <h1>Welcome to My Custom Nginx Page!</h1>
        <p>Finally I created my image.</p> <!-- This is a placeholder for the message from the ConfigMap -->
    </body>
    </html>
